name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: test
      run: ls
      
    - name: Install dependencies
      working-directory: ./eas-go-service
      run: |
        pwd
        ls
        make
      
    - name: test
      run: ls
